Repository vapor/docs, pull requests merged in 2020-07, with the labels that each got.

#498 Fix routing docs
  4.0/docs/routing.md
Labels: updates

#497 Adding features and improving the mkdocs.yml file
  4.0/docs/assets/favicon.png
  4.0/docs/assets/logo.png
  4.0/mkdocs.yml
Labels: updates

#521 Fix HTTPS link in 4.0 index.md
  4.0/docs/index.md
Labels: meta-enhancement

#522 Fix broken link in content.md
  4.0/docs/content.md
Labels: meta-enhancement, typo

#523 Added documentation for validate(query:). Modified validate(_ request…
  4.0/docs/validation.md
Labels: updates

#526 Add page for setting a Custom Working Directory
  4.0/docs/images/set-working-dir-01.png
  4.0/docs/images/set-working-dir-02.png
  4.0/docs/images/set-working-dir-03.png
  4.0/docs/images/set-working-dir-04.png
  4.0/docs/images/set-working-dir-05.png
  4.0/docs/xcode.md
  4.0/mkdocs.yml
Labels: updates

#529 Update references to `app.swift`
  4.0/docs/folder-structure.md
Labels: updates

#534 Add JWT docs
  4.0/docs/authentication.md
  4.0/docs/fluent/schema.md
  4.0/docs/jwt.md
  4.0/mkdocs.yml
Labels: updates
