Repository vapor/docs, pull requests merged in 2020-04, with the labels that each got.

#462 vapor 4.0.0 gm
  4.0/docs/authentication.md
  4.0/docs/environment.md
  4.0/docs/errors.md
  4.0/docs/logging.md
  4.0/docs/middleware.md
  4.0/docs/passwords.md
  4.0/docs/server.md
  4.0/docs/services.md
  4.0/docs/sessions.md
  4.0/docs/testing.md
  4.0/mkdocs.yml
Labels: updates

#471 Added docs for beforeEncode and afterEncode to Content.md
  4.0/docs/content.md
Labels: updates

#465 Add documentation for Docker deploys.
  4.0/docs/deploy/docker.md
  4.0/mkdocs.yml
Labels: updates

#456 Add MongoDB docs for configuration and nested entities
  4.0/docs/fluent/advanced.md
  4.0/docs/fluent/overview.md
  4.0/mkdocs.yml
Labels: updates

#453 Add repository pattern to "upgrading"
  4.0/docs/upgrading.md
Labels: updates

#475 Specify 4.3.0 for the vapor repo in upgrading.md
  4.0/docs/upgrading.md
Labels: updates

#474 # Add Simplified Chinese document guidelines.
  4.0/docs/index.md
Labels: meta-enhancement

#477 Fix typo in CreateStarTag migration
  4.0/docs/fluent/overview.md
Labels: typo
