Repository vapor/docs, pull requests merged in 2022-08, with the labels that each got.

#694 add redis translation
  docs/redis/overview.zh.md
  docs/redis/sessions.zh.md
Labels: translation-update

#697 add advanced sessions translation
  docs/advanced/sessions.zh.md
Labels: translation-update

#698 Add security cryto & passwords translation
  docs/security/crypto.zh.md
  docs/security/passwords.zh.md
Labels: translation-update

#667 Add dutch translation
  docs/advanced/apns.nl.md
  docs/advanced/commands.nl.md
  docs/advanced/files.nl.md
  docs/advanced/middleware.nl.md
  docs/advanced/queues.nl.md
  docs/advanced/server.nl.md
  docs/advanced/services.nl.md
  docs/advanced/sessions.nl.md
  docs/advanced/testing.nl.md
  docs/advanced/websockets.nl.md
  docs/basics/async.nl.md
  docs/basics/client.nl.md
  docs/basics/content.nl.md
  docs/basics/controllers.nl.md
  docs/basics/environment.nl.md
  docs/basics/errors.nl.md
  docs/basics/logging.nl.md
  docs/basics/routing.nl.md
  docs/basics/validation.nl.md
  docs/contributing/contributing.nl.md
  docs/deploy/digital-ocean.nl.md
  docs/deploy/docker.nl.md
  docs/deploy/heroku.nl.md
  docs/deploy/nginx.nl.md
  docs/deploy/supervisor.nl.md
  docs/deploy/systemd.nl.md
  docs/fluent/advanced.nl.md
  docs/fluent/migration.nl.md
  docs/fluent/model.nl.md
  docs/fluent/overview.nl.md
  docs/fluent/query.nl.md
  docs/fluent/relations.nl.md
  docs/fluent/schema.nl.md
  docs/fluent/transaction.nl.md
  docs/getting-started/folder-structure.nl.md
  docs/getting-started/hello-world.nl.md
  docs/getting-started/spm.nl.md
  docs/getting-started/xcode.nl.md
  docs/install/linux.nl.md
  docs/install/macos.nl.md
  docs/leaf/custom-tags.nl.md
  docs/leaf/getting-started.nl.md
  docs/leaf/overview.nl.md
  docs/redis/overview.nl.md
  docs/redis/sessions.nl.md
  docs/security/authentication.nl.md
  docs/security/crypto.nl.md
  docs/security/jwt.md
  docs/security/jwt.nl.md
  docs/security/passwords.nl.md
  docs/upgrading.nl.md
  docs/version/legacy-docs.nl.md
  mkdocs.yml
Labels: help wanted, translation-update

#706 Dutch translation added for PR 700 and PR 702
  docs/advanced/queues.nl.md
  docs/security/authentication.nl.md
Labels: translation-update

#704 add fluent(model, relations, schema) translation
  docs/fluent/model.zh.md
  docs/fluent/overview.zh.md
  docs/fluent/relations.zh.md
  docs/fluent/schema.zh.md
Labels: translation-update

#713 Fix deadlink
  docs/fluent/schema.zh.md
Labels: no-translation-needed

#711 add basics errors translation and fix 404
  docs/basics/errors.zh.md
  docs/basics/logging.zh.md
Labels: translation-update

#715 Add advanced queues translation
  docs/advanced/queues.zh.md
Labels: translation-update

#716 Translation of pr712 and 709 to dutch
  docs/advanced/queues.nl.md
  docs/leaf/overview.nl.md
Labels: translation-update

#717 Add security jwt translation
  docs/security/jwt.zh.md
Labels: translation-update
