Repository vapor/docs, pull requests merged in 2023-08, with the labels that each got.

#875 Updated apns(Chinese) doc.
  docs/advanced/apns.zh.md
Labels: updates, translation-update

#879 Translate controllers section to italian
  docs/basics/controllers.it.md
Labels: translation-update

#860 Request Section
  docs/advanced/request.md
Labels: updates

#884 Translate Request section to Italian
  docs/advanced/request.it.md
Labels: translation-update

#891 Fix redis docs dead links
  docs/redis/overview.md
  docs/redis/overview.nl.md
  docs/redis/overview.zh.md
Labels: no-translation-needed

#890 Add request section option
  mkdocs.yml
Labels: no-translation-needed
