Repository vapor/docs, pull requests merged in 2023-12, with the labels that each got.

#953 Update Command docs to use new AsyncCommand api
  docs/advanced/commands.md
  docs/advanced/commands.nl.md
  docs/advanced/commands.zh.md
Labels: no-translation-needed

#952 update cn doc
  docs/basics/validation.zh.md
Labels: translation-update

#954 Update snippet in server.md
  docs/advanced/server.de.md
  docs/advanced/server.md
  docs/advanced/server.nl.md
  docs/advanced/server.zh.md
Labels: no-translation-needed

#955 Add missing `else` to guard in docs
  docs/basics/controllers.de.md
  docs/basics/controllers.es.md
  docs/basics/controllers.it.md
  docs/basics/controllers.ja.md
  docs/basics/controllers.md
  docs/basics/controllers.zh.md
Labels: invalid code, no-translation-needed
