Repository vapor/docs, pull requests merged in 2023-06, with the labels that each got.

#810 Translate top level docs
  docs/index.it.md
  docs/upgrading.it.md
Labels: translation-update

#814 Update Heroku documentation to deploy a Postgres database
  docs/deploy/heroku.md
  docs/deploy/heroku.nl.md
  docs/deploy/heroku.zh.md
Labels: no-translation-needed

#813 Update hljs and code blocks style
  docs/javascripts/highlight.min.js
  docs/javascripts/startSyntaxHighlighting.js
  docs/javascripts/syntax.js
  docs/stylesheets/syntax.css
  mkdocs.yml
Labels: enhancement, no-translation-needed

#815 Example to populate pivot properties
  docs/fluent/relations.md
Labels: updates

#817 Start Spanish translation
  .github/workflows/translation-issue-template.md
  docs/index.es.md
  mkdocs.yml
Labels: translation-update

#823 Add Spanish translation for linux.md
  docs/install/linux.de.md
  docs/install/linux.es.md
  docs/install/linux.md
  docs/install/linux.nl.md
  docs/install/linux.zh.md
Labels: translation-update

#821 Add Italian translation for installation section
  docs/install/linux.it.md
  docs/install/macos.it.md
Labels: translation-update

#828 Add Spanish translation for routing.md
  docs/basics/routing.es.md
Labels: translation-update

#830 ISSUE-816: Spanish translation for menu entry Fluent->overview.
  docs/fluent/overview.es.md
Labels: translation-update

#834 Fix fluent overview notes
  docs/fluent/overview.es.md
Labels: translation-update

#833 Add Spanish translation for basics/client and basics/validation
  docs/basics/client.es.md
  docs/basics/validation.es.md
  mkdocs.yml
Labels: translation-update

#842 Add Spanish translation for content.md
  docs/basics/content.es.md
Labels: translation-update

#846 Add Spanish translation for basics/logging and basics/environment
  docs/basics/environment.es.md
  docs/basics/logging.es.md
  mkdocs.yml
Labels: translation-update
