Repository vapor/docs, pull requests merged in 2023-11, with the labels that each got.

#928 Add Spanish translation for overview.md
  docs/leaf/overview.es.md
Labels: translation-update

#927 Add Spanish translation for getting-started.md
  docs/leaf/getting-started.es.md
Labels: translation-update

#925 Recommend Swiftly as install method on Linux
  docs/deploy/digital-ocean.md
  docs/install/linux.md
Labels: updates

#931 Add Spanish translation for redis/sessions.md
  docs/redis/sessions.es.md
Labels: translation-update

#930 Add Spanish translation for redis/overview.md
  docs/redis/overview.es.md
Labels: translation-update

#942 Modernize deploy workflow
  .github/workflows/check.yml
  .github/workflows/deploy.yml
Labels: meta-enhancement, no-translation-needed, github_actions

#889 Translate authentication.md to german
  docs/security/authentication.de.md
Labels: translation-update

#943 Update apns.md
  docs/advanced/apns.md
Labels: typo, no-translation-needed

#944 Update highlightjs
  docs/javascripts/highlight.min.js
Labels: meta-enhancement, no-translation-needed

#947 Align apns versions and imports
  docs/advanced/apns.it.md
  docs/advanced/apns.md
  docs/advanced/apns.nl.md
  docs/advanced/apns.zh.md
Labels: no-translation-needed

#941 Add polish translation for leaf getting-started
  docs/leaf/getting-started.pl.md
Labels: translation-update

#939 update cn doc
  docs/deploy/digital-ocean.zh.md
  docs/install/linux.zh.md
Labels: translation-update

#950 Minor Code Fixes to apns.md
  docs/advanced/apns.it.md
  docs/advanced/apns.md
  docs/advanced/apns.nl.md
  docs/advanced/apns.zh.md
Labels: no-translation-needed
