Repository vapor/docs, pull requests merged in 2023-07, with the labels that each got.

#845 Started Polish translation and translated index.md
  .github/workflows/translation-issue-template.md
  docs/index.pl.md
  mkdocs.yml
Labels: translation-update

#840 update cn doc
  docs/deploy/heroku.zh.md
  docs/getting-started/folder-structure.zh.md
  docs/getting-started/hello-world.zh.md
  docs/getting-started/spm.zh.md
Labels: translation-update

#848 Added translation for install section of documentation to Polish
  docs/install/linux.pl.md
  docs/install/macos.pl.md
Labels: translation-update

#847 Add Spanish translation for basics/controllers and basics/errors
  docs/basics/controllers.es.md
  docs/basics/errors.es.md
Labels: translation-update

#841 Start Korean translation
  .github/workflows/translation-issue-template.md
  docs/getting-started/folder-structure.ko.md
  docs/getting-started/hello-world.ko.md
  docs/getting-started/spm.ko.md
  docs/getting-started/xcode.ko.md
  docs/index.ko.md
  docs/install/linux.ko.md
  docs/install/macos.ko.md
  mkdocs.yml
Labels: translation-update

#854 Update Search Index Script for new languages
  README.md
  fixSearchIndex.swift
Labels: translation-update

#852 Getting Started - Polish translation
  docs/getting-started/folder-structure.pl.md
  docs/getting-started/hello-world.pl.md
  docs/getting-started/spm.pl.md
  docs/getting-started/xcode.pl.md
Labels: translation-update

#843 Extend lifecycle handler example
  docs/advanced/services.md
  docs/advanced/services.nl.md
  docs/advanced/services.zh.md
Labels: updates, no-translation-needed, translation-update

#855 Add dark mode support
  mkdocs.yml
Labels: meta-enhancement, no-translation-needed

#858 Add leaf syntax highlighting lib link
  docs/leaf/getting-started.md
Labels: enhancement

#862 update cn doc
  docs/leaf/getting-started.zh.md
Labels: translation-update

#867 Add new templates for vapor/penny-bot#81
  .github/translation_needed.description.leaf
  README.md
Labels: no-translation-needed
