Repository vapor/docs, pull requests merged in 2024-05, with the labels that each got.

#976 update cn doc
  docs/advanced/websockets.zh.md
Labels: translation-update

#977 Update JWT references for JWTKit 5
  docs/security/authentication.md
  docs/security/jwt.md
Labels: updates

#980 fix typo & add missing 'with' argument label
  docs/security/authentication.de.md
  docs/security/authentication.it.md
  docs/security/authentication.md
  docs/security/authentication.nl.md
  docs/security/authentication.zh.md
Labels: no-translation-needed
