Repository vapor/docs, pull requests merged in 2024-01, with the labels that each got.

#956 Remove the use of `load(on:)` in relations.md
  docs/fluent/relations.md
Labels: invalid code, updates

#958 Add Chinese translation for relations.md
  docs/fluent/relations.zh.md
Labels: translation-update

#959 fixed typo
  docs/deploy/digital-ocean.zh.md
Labels: no-translation-needed

#960 fix typo Swiflty => Swiftly
  docs/deploy/digital-ocean.md
Labels: no-translation-needed

#936 Add Spanish translation for schema.md
  docs/fluent/schema.es.md
Labels: translation-update
