Repository vapor/docs, pull requests merged in 2025-04, with the labels that each got.

#1075 Suggest "Vapor for VS Code" extension
  docs/getting-started/hello-world.it.md
  docs/getting-started/hello-world.md
  docs/leaf/getting-started.es.md
  docs/leaf/getting-started.it.md
  docs/leaf/getting-started.ja.md
  docs/leaf/getting-started.md
  docs/leaf/getting-started.nl.md
  docs/leaf/getting-started.pl.md
  docs/leaf/getting-started.zh.md
Labels: no-translation-needed

#1076 Translate alert titles in Italian
  docs/getting-started/hello-world.it.md
  docs/leaf/custom-tags.it.md
  docs/leaf/getting-started.it.md
  docs/leaf/overview.it.md
  docs/redis/overview.it.md
  docs/security/authentication.it.md
  docs/security/crypto.it.md
  docs/upgrading.it.md
Labels: no-translation-needed, translation-update

#1077 NEW: Updated getting-started.es.md and hello-world.es.md files
  docs/getting-started/hello-world.es.md
  docs/leaf/getting-started.es.md
Labels: translation-update
