Repository vapor/docs, pull requests merged in 2025-01, with the labels that each got.

#1046 fix(jwt.md): changed "botha" to "both a"
  docs/security/jwt.md
Labels: no-translation-needed

#1034 Add Spanish translation for deploy/fly.md
  docs/basics/async.es.md
  docs/deploy/fly.es.md
  docs/deploy/fly.md
  docs/deploy/fly.nl.md
  docs/deploy/fly.zh.md
Labels: translation-update

#1045 Feature/translation EN > ES heroku.es.md
  docs/deploy/heroku.es.md
  docs/deploy/heroku.md
Labels: translation-update

#1044 Feature/translation EN > ES digital-ocean.es.md
  docs/deploy/digital-ocean.es.md
  docs/deploy/digital-ocean.md
Labels: translation-update

#1037 Translation EN > ES docker.es.md
  docs/deploy/docker.es.md
  docs/deploy/docker.md
Labels: translation-update

#1047 Feature/translation EN > ES sessions.es.md
  docs/advanced/sessions.es.md
  docs/advanced/sessions.md
Labels: translation-update

#1036 Feature/translation EN > ES jwt.es.md file
  docs/security/jwt.es.md
  docs/security/jwt.md
Labels: translation-update

#1048 Feature/translation EN > ES websockets.es.md
  docs/advanced/websockets.es.md
Labels: translation-update

#1049 Feature/translation EN > ES release-notes.es.md
  docs/release-notes.es.md
  mkdocs.yml
Labels: translation-update

#1043 Translation EN > ES tracing.es.md
  docs/advanced/tracing.es.md
Labels: translation-update

#1052 Update of custom validator documentation in Spanish
  docs/basics/errors.es.md
  docs/basics/validation.es.md
  docs/basics/validation.md
Labels: translation-update

#1051 Translation EN > ES: request.es.md
  docs/advanced/request.es.md
  docs/advanced/request.md
  mkdocs.yml
Labels: translation-update

#1053 Refine Leaf cache documentation
  docs/leaf/getting-started.md
Labels: updates

#1057 Updating getting-started.es.md file
  docs/leaf/getting-started.es.md
Labels: translation-update

#1059 NEW: Updating testing.es.md file
  docs/advanced/testing.es.md
Labels: translation-update
