Repository vapor/docs, pull requests merged in 2025-03, with the labels that each got.

#1067 Translation added: Spanish (es), Nederlands (nl) and Chinese (zh)
  docs/deploy/heroku.es.md
  docs/deploy/heroku.nl.md
  docs/deploy/heroku.zh.md
Labels: translation-update

#1068 Reordered languages & added original names in translation_needed
  .github/translation_needed.description.leaf
  mkdocs.yml
Labels: meta-enhancement, no-translation-needed

#1069 Update schema.md field constraints list
  docs/fluent/schema.md
Labels: updates

#1071 NEW: fluent > schema.es.md translation
  docs/fluent/schema.es.md
Labels: translation-update

#1072 Toolbox v19 update
  docs/getting-started/xcode.de.md
  docs/getting-started/xcode.es.md
  docs/getting-started/xcode.it.md
  docs/getting-started/xcode.ja.md
  docs/getting-started/xcode.ko.md
  docs/getting-started/xcode.md
  docs/getting-started/xcode.nl.md
  docs/getting-started/xcode.pl.md
  docs/getting-started/xcode.zh.md
  docs/install/linux.it.md
  docs/install/linux.md
  docs/install/macos.it.md
  docs/install/macos.md
Labels: updates

#1073 Fix "Model Coupling" example in Schema docs
  docs/fluent/schema.es.md
  docs/fluent/schema.md
Labels: no-translation-needed

#1074 NEW: updating linux.es.md and macos.es.md texts #1072
  docs/install/linux.es.md
  docs/install/macos.es.md
Labels: translation-update
